export const testLayout = [
  {
    x: 0,
    y: 0,
    w: 1,
    h: 2,
    i: '0',
    name: 'Item0',
    content: 'Lorem Ipsum',
    resizable: true,
    draggable: true,
    static: false,
  },
  {
    x: 1,
    y: 0,
    w: 1,
    h: 2,
    i: '1',
    name: 'Item1',
    content: 'Lorem Ipsum',
    resizable: true,
    draggable: true,
    static: false,
  },
  {
    x: 2,
    y: 0,
    w: 1,
    h: 2,
    i: '2',
    name: 'Item2',
    content: 'Lorem Ipsum',
    resizable: true,
    draggable: true,
    static: false,
  },
  {
    x: 3,
    y: 0,
    w: 1,
    h: 2,
    i: '3',
    name: 'Hello world',
    content: 'Lorem Ipsum',
    resizable: true,
    draggable: true,
    static: false,
  },
  {
    x: 4,
    y: 0,
    w: 1,
    h: 2,
    i: '4',
    name: 'Item4',
    content: 'Lorem Ipsum',
    resizable: true,
    draggable: true,
    static: false,
  },
  {
    x: 5,
    y: 0,
    w: 1,
    h: 2,
    i: '5',
    name: 'Item5',
    content: 'Lorem Ipsum',
    resizable: false,
    draggable: false,
    static: false,
  },
  {
    x: 6,
    y: 0,
    w: 1,
    h: 2,
    i: '6',
    name: 'Item6',
    content: 'Lorem Ipsum',
    resizable: true,
    draggable: true,
    static: false,
  },
  {
    x: 7,
    y: 0,
    w: 1,
    h: 2,
    i: '7',
    name: 'Item7',
    content: 'Lorem Ipsum',
    resizable: true,
    draggable: true,
    static: false,
  },
  {
    x: 8,
    y: 0,
    w: 1,
    h: 2,
    i: '8',
    name: 'Item8',
    content: 'Lorem Ipsum',
    resizable: true,
    draggable: true,
    static: false,
  },
  {
    x: 9,
    y: 0,
    w: 1,
    h: 2,
    i: '9',
    name: 'Item9',
    content: 'Lorem Ipsum',
    resizable: true,
    draggable: true,
    static: false,
  },
  {
    x: 10,
    y: 0,
    w: 1,
    h: 2,
    i: '10',
    name: 'Item10',
    content: 'Lorem Ipsum',
    resizable: true,
    draggable: true,
    static: false,
  },
  {
    x: 11,
    y: 0,
    w: 1,
    h: 2,
    i: '11',
    name: 'Item11',
    content: 'Lorem Ipsum',
    resizable: true,
    draggable: true,
    static: false,
    minY: 4,
  },
  {
    x: 0,
    y: 3,
    w: 1,
    h: 2,
    i: '12',
    name: 'Item12',
    content: 'Lorem Ipsum',
    resizable: true,
    draggable: true,
    static: false,
  },
  {
    x: 1,
    y: 3,
    w: 1,
    h: 2,
    i: '13',
    name: 'Item13',
    content: 'Lorem Ipsum',
    resizable: true,
    draggable: true,
    static: false,
  },
  {
    x: 2,
    y: 3,
    w: 1,
    h: 2,
    i: '14',
    name: 'Item14',
    content: 'Lorem Ipsum',
    resizable: true,
    draggable: true,
    static: false,
  },
  {
    x: 3,
    y: 3,
    w: 1,
    h: 2,
    i: '15',
    name: 'Item15',
    content: 'Lorem Ipsum',
    resizable: true,
    draggable: true,
    static: false,
  },
  {
    x: 4,
    y: 3,
    w: 1,
    h: 2,
    i: '16',
    name: 'Item16',
    content: 'Lorem Ipsum',
    resizable: true,
    draggable: true,
    static: false,
  },
  {
    x: 5,
    y: 3,
    w: 1,
    h: 2,
    i: '17',
    name: 'Item17',
    content: 'Lorem Ipsum',
    resizable: true,
    draggable: true,
    static: false,
  },
  {
    x: 6,
    y: 3,
    w: 1,
    h: 2,
    i: '18',
    name: 'Item18',
    content: 'Lorem Ipsum',
    resizable: true,
    draggable: true,
    static: false,
  },
  {
    x: 7,
    y: 3,
    w: 1,
    h: 2,
    i: '19',
    name: 'Item19',
    content: 'Lorem Ipsum',
    resizable: true,
    draggable: true,
    static: false,
  },
]
